### PR TITLE
Fixed Eqn A.8 (missing minus sign)

### PR DESCRIPTION
**Pull request by bmurphy-usgs**
This pull request inserts the missing minus sign from Eqn A.8 of Amm & Viljanen 1999 and thereby fixes the problem raised in Issue #1. It also includes an update to the version tag.

### CODE REVIEW

**Comment by greglucas** [comment]
The Travis build is complaining because of the indentation on the equation. Do you have flake8 on your system to test the style? I think you can just force-push to your branch and it will automatically test again.

**Comment by bmurphy-usgs** [comment]
Alright @greglucas, I think things are now good to go. (Sorry for the extra commit -- I haven't used flake8 before, but it seems like the rules it follows are slightly different than those laid out in PEP8 [e.g., by default it only complains about line lengths >100 char, but I think PEP8 mandates 80 char], and so took me an extra commit to figure out how to appease the CI).

**Comment by greglucas** [comment]
Sorry about that, Ben! I messed you up by changing that to 100 characters in the `setup.cfg` file as a personal preference to go against the pep8 standards. I personally prefer slightly longer lines when writing math equations so that they make a little more sense by being able to group a few more terms together.

Closes #1

**Comment by bmurphy-usgs** [comment]
@greglucas 100 characters certainly makes things easier! Just took me a bit to figure out why things I thought should be failing weren't, and vice versa. And the whole line continuation indent thing still baffles me... most format-checking tools seem to take a harder stance on this than PEP8, but it's often unclear to me what they actually expect (I'm thinking specifically of PyCharm here).

**Pull request merged**
